# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CovNewbie' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for CovNewbie

  pod 'Google-Mobile-Ads-SDK'

  target 'CovNewbie-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CovNewbieTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'CovNewbie-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for CovNewbie-tvOS

end
